# Generated by Django 2.2 on 2021-04-15 07:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_category_is_container'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Формат номера! +996(555)123123', regex='^\\+996\\d{9}$')], verbose_name='Телефон')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Итого к оплате')),
            ],
            options={
                'verbose_name': 'Оформление заказа',
                'verbose_name_plural': 'Оформление заказа',
            },
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элемент заказа', 'verbose_name_plural': 'Элементы заказа'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='phone',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_big',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество маленькой порции'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_small',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество большой порции'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Order', verbose_name='Заказ'),
        ),
    ]
