# Generated by Django 2.2 on 2021-04-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210416_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_big',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость большой порции'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_small',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость маленькой порции'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_big',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество большой порции'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_small',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество маленькой порции'),
        ),
    ]
