# Generated by Django 2.2 on 2021-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20210416_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_container',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Колличество контейнеров'),
        ),
    ]
