# Generated by Django 2.2 on 2021-02-13 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210213_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория блюда',
                'verbose_name_plural': 'Категории блюд',
            },
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main-banner', verbose_name='Главный баннер'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('is_available', models.BooleanField(default=True, verbose_name='Есть в наличии?')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='SLUG')),
                ('portion', models.CharField(max_length=50, null=True, verbose_name='Порция')),
                ('price', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='Цена')),
                ('portion_two', models.CharField(max_length=50, null=True, verbose_name='Пол порции')),
                ('price_two', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
