# Generated by Django 2.2 on 2021-02-13 15:23

import apps.main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.main.utils.get_product_upload_path, verbose_name='Изображение'),
        ),
    ]
