# Generated by Django 2.2 on 2021-02-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_populate',
            field=models.BooleanField(default=False, verbose_name='Популярное?'),
        ),
    ]
