# Generated by Django 2.2 on 2021-02-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
