# Generated by Django 2.2 on 2021-03-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
