# Generated by Django 2.2 on 2021-03-10 16:52

import apps.main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=apps.main.utils.get_product_upload_path, verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Баннер для старницы о нас',
                'verbose_name_plural': 'Баннер для старницы о нас',
            },
        ),
    ]
