# Generated by Django 2.2 on 2021-03-11 16:47

import apps.main.utils
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_aboutusbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(null=True, upload_to=apps.main.utils.get_product_upload_path, verbose_name='Баннер')),
                ('description_one', ckeditor.fields.RichTextField(null=True, verbose_name='Текст№1')),
                ('description_two', ckeditor.fields.RichTextField(null=True, verbose_name='Текст№2')),
                ('description_three', ckeditor.fields.RichTextField(null=True, verbose_name='Текст№3')),
                ('description_four', ckeditor.fields.RichTextField(null=True, verbose_name='Текст№4')),
            ],
            options={
                'verbose_name': 'Старница о нас',
                'verbose_name_plural': 'Старница о нас',
            },
        ),
        migrations.CreateModel(
            name='SliderAboutUsOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=apps.main.utils.get_product_upload_path, verbose_name='Слайдер')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('about_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_one', to='main.AboutUs', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Слайдер для страницы о нас №1',
                'verbose_name_plural': 'Слайдер для страницы о нас №1',
            },
        ),
        migrations.CreateModel(
            name='SliderAboutUsThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=apps.main.utils.get_product_upload_path, verbose_name='Слайдер')),
                ('about_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_three', to='main.AboutUs', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Слайдер для страницы о нас №3',
                'verbose_name_plural': 'Слайдер для страницы о нас №3',
            },
        ),
        migrations.CreateModel(
            name='SliderAboutUsTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=apps.main.utils.get_product_upload_path, verbose_name='Слайдер')),
                ('about_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_two', to='main.AboutUs', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Слайдер для страницы о нас №2',
                'verbose_name_plural': 'Слайдер для страницы о нас №2',
            },
        ),
        migrations.DeleteModel(
            name='AboutUsBanner',
        ),
    ]
