# Generated by Django 2.2 on 2021-03-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210311_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideraboutusone',
            name='image',
        ),
    ]
