# Generated by Django 2.2 on 2021-03-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210311_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_main',
            field=models.TextField(null=True, verbose_name='Текст на главной'),
        ),
    ]
