# Generated by Django 2.2 on 2021-04-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contact_delivery_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_container',
            field=models.BooleanField(default=False, verbose_name='Не должно быть контейнера?'),
        ),
    ]
